orderapp/urls.py
from django.urls import path
from orderapp import views

app_name = 'orderapp'


urlpatterns = [
    path('add/<pk>', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),

]

shopapp/urls.py
from django.urls import path
from . import views
app_name = 'shopapp'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>', views.ProductDetail.as_view(), name='productdetail'),

]

shoppo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls')),
    path('account/', include('loginapp.urls')),
    path('shop/', include('orderapp.urls')),
    path('payment/', include('paymentapp.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/models.py
from django.db import models


# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"


class Product(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=265)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    preview_text = models.TextField(
        max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created', ]

shopapp/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView

from django.contrib.auth.mixins import LoginRequiredMixin

from shopapp.models import Product
# Create your views here.


class Home(ListView):
    model = Product
    template_name = 'shopapp/home.html'


class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'shopapp/productdetail.html'

templates/shopapp/home.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2 class="display-4 py-5">
        Featured Product
    </h2>
    
    <div class="container">
        <div class="row">
            {% for product in object_list %}

        

   
        <div class="col-md-6 col-sm-12 col-lg-3">
        <figure class="card card-product">
            <div class="img-wrap">
                <img src="{{product.mainimage.url}}" alt="" width= 100%; height=300px;>

            </div>
            <figcaption class="info-wrap">
                <h6 class="title"><a href="{% url 'shopapp:productdetail' pk=product.pk %}">{{product.name}}</a></h6>


                <div class="action-wrap">
                    <div class="price-wrap5">

                    
                        <span class="price-new">&#2547; {{product.price | floatformat:2}}</span><br>
                        <span class="price-old"><strike>&#2547; {{product.old_price | floatformat:2}}</strike></span>
                    </div>
                </div>
                </figcaption>
            </figure>
        
        </div>
        {% endfor %}
</div>
</div>

</div>

{% endblock %}

templates/shopapp/productdetail.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-5">
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div class="">
                            <a href="">
                                <img src="{{object.mainimage.url}}" width="450px" alt="">
                            </a>

                        </div>
                    </div>

                </article>
            </aside>
            <aside class="col-md-7">
                <article class="card-body p-5">
                    <h3 class="title mp-3">{{object.name}}</h3>
                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">BDT &#2547</span>
                            <span class="num">{{object.price}}</span>
                            
                        </span>
                    </p>

                <dt class="item-property">
                    Description
                    <dd>
                        <p>{{object.detail_text | linebreaks }}</p>
                    </dd>
                </dt>
                <a href="{% url 'orderapp:add' pk=object.pk %}" class="btn btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i>Add to Cart</a>
                </article>

            </aside>
        </div>
    </div>
</div>
{% endblock %}