orderapp/urls.py
from django.urls import path
from orderapp import views

app_name = 'orderapp'


urlpatterns = [
    path('add/<pk>', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),

]

paymentapp/urls.py
from django.urls import path
from . import views

app_name = 'paymentapp'


urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),

]

shopapp/urls.py
from django.urls import path
from . import views
app_name = 'shopapp'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>', views.ProductDetail.as_view(), name='productdetail'),

]

shoppo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls')),
    path('account/', include('loginapp.urls')),
    path('shop/', include('orderapp.urls')),
    path('payment/', include('paymentapp.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orderapp/models.py
from django.db import models

# Create your models here.
from shopapp.models import Product
from django.conf import settings


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name='cart')
    item = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='cart')
    quantity = models.IntegerField(default=1)
    purchase = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} X {self.item}'

    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '0.2f')
        return float_total


class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True, null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)

    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        return total

orderapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.contrib.auth.decorators import login_required

from orderapp.models import Cart, Order
from shopapp.models import Product
from django.contrib import messages
# Create your views here.


@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get_or_create(
        item=item, user=request.user, purchase=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item[0].quantity += 1
            order_item[0].save()
            messages.info(request, "This item has been updated . ")
            return redirect('shopapp:home')

        else:
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart .")
            return redirect('shopapp:home')

    else:
        order = Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        messages.info(request, "This item was added to your cart .")
        return redirect('shopapp:home')


@login_required
def cart_view(request):
    carts = Cart.objects.filter(user=request.user, purchase=False)
    orders = Order.objects.filter(user=request.user, ordered=False)
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'orderapp/cart.html', context={'carts': carts, 'order': order})

    else:
        messages.warning(request, "You don't have any item in your cart!")
        return redirect('shopapp:home')


@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(
                item=item, user=request.user, purchase=False)
            order_item = order_item[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("orderapp:cart")

        else:
            messages.info(request, "This order was not in your cart.")
            return redirect("shopapp:home")

    else:
        messages.info(request, "You don't have an active order")
        return redirect("shopapp:home")


@login_required
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(
                item=item, user=request.user, purchase=False)
            order_item = order_item[0]
            if order_item.quantity >= 1:
                order_item.quantity += 1
                order_item.save()
                messages.info(
                    request, f'{item.name} quantity has been updated')
                return redirect('orderapp:cart')

        else:
            messages.info(request, f'{item.name} is not in your cart')

    else:
        messages.info(request, "You don't have any an active order!")
        return redirect('shopapp:home')


@login_required
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(
                item=item, user=request.user, purchase=False)
            order_item = order_item[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(
                    request, f'{item.name} quantity has been updated')
                return redirect('orderapp:cart')
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
                messages.warning(
                    request, f'{item.name} has been removed from your cart')
                return redirect('shopapp:home')

        else:
            messages.info(request, f'{item.name} is not in your cart')

    else:
        messages.info(request, "You don't have any an active order!")
        return redirect('shopapp:home')

templates/orderapp/cart.html
{% extends 'base.html' %}

{%  block content %}

<div class="container my-5">

    <div class="my-5">
        <h2>Your Cart</h2>

    </div>

    <table class="table table-hover">
        <thead>
            <tr >
                <th scope="col" width='155'>#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for cart in carts %}
            <tr>
                <th scope = "row">{{ forloop.counter }}</th>
                <td>{{ cart.item.name }}</td>
                <td>
                    <a href="{% url 'orderapp:decrease' pk=cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
                    {{cart.quantity}}
                    <a href="{% url 'orderapp:increase' pk=cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
                </td>
                <td align="center">&#2547; {{cart.get_total}}</td>
                <td><a href="{% url 'orderapp:remove' pk=cart.item.pk %}" class="btn btn-danger btn-sm">Remove From Cart</a></td>
            </tr>


            {% endfor %}
            <tr>
                <th scope="row"></th>
                <td colspan="2">Total</td>
                <td align="center">&#2547; {{order.get_totals}}</td>
                <td></td>
            </tr>
            <tr>
                <th scope="row"></th>
                <td colspan="4" class="text-right">
                    <a href="{% url 'shopapp:home'%}" class="btn btn-warning mr-4">Continue Shopping</a>
                    <a href="{% url 'paymentapp:checkout'%}" class="btn btn-success mr-4">Proceed To Checkout</a>
                </td>
            </tr>
        </tbody>

    </table>
</div>

{% endblock %}