loginapp/urls.py
from django.urls import path
from . import views

app_name = 'loginapp'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.userprofile, name='profile'),

]

orderapp/urls.py
from django.urls import path
from orderapp import views

app_name = 'orderapp'


urlpatterns = [
    path('add/<pk>', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),

]

paymentapp/urls.py
from django.urls import path
from . import views

app_name = 'paymentapp'


urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),

]

shopapp/urls.py
from django.urls import path
from . import views
app_name = 'shopapp'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>', views.ProductDetail.as_view(), name='productdetail'),

]

shoppo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls')),
    path('account/', include('loginapp.urls')),
    path('shop/', include('orderapp.urls')),
    path('payment/', include('paymentapp.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta  http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>{% block title %} Shoppo E-com | Webservice {% endblock %}</title>
  </head>
  <body>


    <style>
      .card{
        height: 350px;
      }
      .card-product::after{
        content: "";
        display: table;
        clear: both;
        visibility: hidden;

      }

      .card-product .price-new, .card-product .price{
        margin-right: 5px;
      }
      .card-product .price-old{
        color:#999;
      }
      .card-product .img-wrap{
        border-radius: 3px 3px 0 0;
        overflow:hidden;
        position:relative;
        height:220px;
        text-align:center;
      }
      .card-product .img-wrap img{
        max-width:100%;
        max-height: 100%;
        object-fit: cover;
      }

      .card-product .info-wrap{
        overflow:hidden;
        padding:15px;
        border-top: 1px solid #eee;

      }
      .card-product .action-wrap{
        padding-top: 4px;
        margin-top: 4px;

      }

      .card-product .bottom-wrap{
        padding: 15px;
        border-top : 1px solid #eee
      }
      .card-product .title{
        margin-top:0px;

      }




    </style>

    {%include 'navbar.html'%}

    <div class="container">
      <div class="messages container mt-2">
        {% if messages %}
          {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
          {{message}}
          <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
          {% endfor %}
        {% endif %}
      </div>


      {% block content %}
      {% endblock %}
    </div>
  </div>

    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  </body>
</html>

templates/navbar.html
{% load cart_tag %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'shopapp:home' %}">shopp.com</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                  {% if request.user.is_authenticated %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'shopapp:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'orderapp:cart' %}"><i class="fa fa-shopping-cart">( <span class="badge badge-light">{{request.user | cart_total}}</span> )</i></a>
                  
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-user-tie"></i>  {{request.user.profile.username}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'loginapp:profile' %}">Profile</a>
                      <a class="dropdown-item" href="{% url 'paymentapp:orders' %}">Orders</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'loginapp:logout' %}">Logout</a>
                    </div>
                  </li>
                  {% else %}
                  <li class="nav-item">
                      <a href="{% url 'loginapp:login' %}" class="btn btn-primary">Login</a>
                  </li>
                  {% endif %}
              </ul>
            </div>
          </nav>