paymentapp/urls.py
from django.urls import path
from . import views

app_name = 'paymentapp'


urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),

]

shopapp/urls.py
from django.urls import path
from . import views
app_name = 'shopapp'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>', views.ProductDetail.as_view(), name='productdetail'),

]

shoppo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls')),
    path('account/', include('loginapp.urls')),
    path('shop/', include('orderapp.urls')),
    path('payment/', include('paymentapp.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paymentapp/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    address = models.CharField(max_length=264, blank=True)
    zipode = models.CharField(max_length=10, blank=True)
    city = models.CharField(max_length=30, blank=True)
    country = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return f'{self.user.profile.username} billing address'

    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]

        for field_name in field_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True

    class Meta:
        verbose_name_plural = 'Billing Addresses'

paymentapp/forms.py
from django import forms
from paymentapp.models import BillingAddress


class BillingForm(forms.ModelForm):
    class Meta:
        model = BillingAddress
        fields = ['address', 'zipode', 'city', 'country', ]

paymentapp/views.py
from django.db import reset_queries
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse

from orderapp.models import Order, Cart
from paymentapp.forms import BillingAddress
from paymentapp.forms import BillingForm
from django.contrib import messages

from django.contrib.auth.decorators import login_required

import requests
from sslcommerz_python.payment import SSLCSession
from decimal import Decimal
import socket
from django.views.decorators.csrf import csrf_exempt


@login_required
def checkout(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    saved_address = saved_address[0]
    form = BillingForm(instance=saved_address)
    if request.method == 'POST':
        form = BillingForm(request.POST, instance=saved_address)
        if form.is_valid():
            form.save()
            form = BillingForm(instance=saved_address)
            messages.success(request, "Your address has been updated")
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order_items = order_qs[0].orderitems.all()
    order_total = order_qs[0].get_totals()
    return render(request, 'paymentapp/checkout.html', context={'form': form, 'order_items': order_items, 'order_total': order_total, 'saved_address': saved_address})


@login_required
def payment(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)

    if not saved_address[0].is_fully_filled():
        messages.info(request, f'Please complete shipping address !')
        return redirect('paymentapp:checkout')

    if not request.user.profile.is_fully_filled():
        messages.info(request, f'Please complete profile first')
        return redirect('loginapp:profile')
    store_id = 'shopp605b60f588ee3'
    API_key = 'shopp605b60f588ee3@ssl'
    mypayment = SSLCSession(sslc_is_sandbox=True, sslc_store_id=store_id,
                            sslc_store_pass=API_key)

    status_url = request.build_absolute_uri(reverse('paymentapp:complete'))
    mypayment.set_urls(success_url=status_url, fail_url=status_url,
                       cancel_url=status_url, ipn_url=status_url)

    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order_items = order_qs[0].orderitems.all()
    order_items_count = order_qs[0].orderitems.count()
    order_total = order_qs[0].get_totals()
    saved_address = saved_address[0]

    mypayment.set_product_integration(total_amount=Decimal(order_total), currency='BDT', product_category='Mixed',
                                      product_name=order_items, num_of_item=order_items_count, shipping_method='Courier', product_profile='None')

    current_user = request.user
    mypayment.set_customer_info(name=current_user.profile.full_name, email=current_user.email, address1=current_user.profile.address_1,
                                address2=current_user.profile.address_1, city=current_user.profile.city, postcode=current_user.profile.zipcode, country=current_user.profile.country, phone=current_user.profile.phone)

    mypayment.set_shipping_info(shipping_to=current_user.profile.full_name, address=saved_address.address,
                                city=saved_address.city, postcode=saved_address.zipode, country=saved_address.country)

    response_data = mypayment.init_payment()

    return redirect(response_data['GatewayPageURL'])


@csrf_exempt
def complete(request):
    if request.method == 'POST' or request.method.method == 'post':
        payment_data = request.POST
        status = payment_data['status']
        print(status)

        if status == 'VALID':
            tran_id = payment_data['tran_id']
            val_id = payment_data['val_id']
            messages.success(request, f'Your Payment Completed Successfully !')
            return HttpResponseRedirect(reverse('paymentapp:purchase', kwargs={'val_id': val_id, 'tran_id': tran_id},))

        elif status == 'FAILED':
            messages.warning(
                request, f'Your Payment Failed ! Please try again .')
        else:
            messages.warning(
                request, f'You Cancled your Payment')

    return render(request, 'paymentapp/complete.html', context={})


@login_required
def purchase(request, val_id, tran_id):
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order = order_qs[0]
    orderId = tran_id
    order.ordered = True
    order.orderId = orderId
    order.paymentId = val_id
    order.save()
    cart_items = Cart.objects.filter(user=request.user, purchase=False)
    for item in cart_items:
        item.purchase = True
        item.save()
    return HttpResponseRedirect(reverse('shopapp:home'))


@login_required
def order_view(request):
    try:
        orders = Order.objects.filter(user=request.user, ordered=True)
        context = {'orders': orders}

    except:
        messages.warning(request, "You dont have an active order!")
        return redirect('shopapp:home')

    return render(request, 'paymentapp/order.html', context)

templates/paymentapp/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="container mt-5">
    <h2 class="mb-3">
        Shipping Address > <span class="text-muted">Checkout</span>

    </h2>
    <div class="row">
        <div class="col-md-9">
            <div class="card mb-5" style="height:auto;">
                <div class="card-body">
                    <form action="" method="post">
                        {{form|crispy}}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success float-right">Save Address</button>
                    </form>
                </div>

            </div>

        </div>

        <div class="col-md-3">
            <div class="card" style="height: auto;">
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for order_item in order_items %}
                        <li class="list-group-item"> {{order_item.item.name}} x {{order_item.quantity}}</li>
        
        
                        {% endfor %}
                    </ul>
                </div>
        
                <div class="card-footer">
                    <span class="float-left"><b>Order Total</b></span>
                    <span class="float-right"><b>{{order_total | floatformat:2}}</b></span>
                </div>
        
            </div>
            <br>
            <br>

            {% if saved_address.is_fully_filled %}
            <a href="{% url 'paymentapp:payment' %}" class="btn btn-warning text-center"style="margin-left:50px;">Make Payment</a>



            {% else %}
            <div class="alert alert-info">
                <p>Please fill up all the information to make payment !</p>
            </div>


            {% endif %}
        </div>
    </div>

</div>




{% endblock %}

templates/paymentapp/complete.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="5; url={% url 'shopapp:home' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Payment Status</title>
  </head>
  <body>
    <div class="container">
        <div class="messages container mt-2">
          {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
            {% endfor %}
          {% endif %}
            </div>
  
  
        {% block content %}
        {% endblock %}
      </div>
    </div>


  

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  </body>
</html>

templates/paymentapp/order.html
{% extends 'base.html '%}

{% block content %}

<div class="container mt-5">
    <h2 class="text-center"><strong>Your Orders</strong></h2>
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-5" style="height: auto;">
                <div class="table-responsive">
                    <div class="table">
                        <table>
                        <thead>

                            <tr>

                                <th scope="col">#</th>
                                <th scope="col">Order Id</th>
                                <th scope="col">Products</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for order in orders %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td><a href="">{{order.orderId}}</a></td>
                                <td>
                                    {% for item in order.orderitems.all %}
                                        {{item}}
                                    {% endfor %}
                                </td>
                                <td><span class="badge badge-primary">Processing Your Order</span></td>

                            </tr>

                            {% endfor %}
                        </tbody>
                    </table>

                    </div>
                </div>


            </div>
            <div class="col-md-12 my-5 text-center">
                <a href="{% url 'shopapp:home' %}">Back to Home</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}